version: '3'
services:
  client:
    container_name: client
    build: ./client
    image: debug_client
    ports: 
      - 8080:8080
    working_dir: /code
    volumes:
      - type: bind
        source: ./client
        target: /code
    command: [ "http-server" ]
  api:
    image: node:12.18.4
    ports: 
      - 3000:3000
    environment: 
      - PGUSER=cablegram
      - PGHOST=db
      - PGPASSWORD=cablegram_password
      - PGDATABASE=cablegram
      - PGPORT=5432
      - NODE_ENV=development
    depends_on:
      - db
    command: bash -c "npm install && npm run dev"
  db:
    image: postgres:latest
    volumes:
      - "dbdata:/var/lib/postgresql/data"
      - "./db/setup/:/docker-entrypoint-initdb.d/:ro"
    environment: 
      - POSTGRES_DB=cablegram
      - POSTGRES_USER=cablegram
      - POSTGRES_PASSWORD=cablegram_password
volumes:
  dbdata:

