version: '3'
services: 
  api: 
    image: 'node:latest'
    working_dir: /code
    ports: 
      - 3000:3000
    environment: 
      - PGUSER=futureproof
      - PGHOST=db
      - PGPASSWORD=cablegram_password
      - PGDATABASE=cablegram
      - PGPORT=5432
    depends_on:
      - db
    volumes:
      - type: bind
        source: ./api
        target: /code
    command: bash -c "npm install && npm run seedDev && npm run dev"
  db:
    image: postgres:latest
    volumes:
      - "dbdata:/var/lib/postgresql/data"
      - "./db/setup/:/docker-entrypoint-initdb.d/:ro"
    environment: 
      - POSTGRES_DB=cablegram
      - POSTGRES_USER=futureproof
      - POSTGRES_PASSWORD=cablegram_password
  volumes:
     dbdata: 
    

